name: CI Workflow

on:
  push:
    branches:
      - main  # Esto se activa cuando hay un push a la rama principal

jobs:
  build:
    runs-on: ubuntu-latest  # Se ejecutar치 en un entorno Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Esto descarga el c칩digo del repositorio

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Especifica la versi칩n de Node.js que deseas usar

    - name: Install dependencies
      run: npm install  # Esto instalar치 las dependencias de Node.js, si las tienes

    - name: Run build
      run: echo "Building and testing app..."  # Esto solo es un ejemplo; puedes reemplazarlo con tus comandos reales
